baseURL = "https://trwicks.github.io/"
languageCode = "en"


googleAnalytics = "G-EL3Q5XRTYP"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[imaging]
  anchor = 'Center'