# Markdown renderer configuration
[goldmark]
[goldmark.renderer]
    unsafe = false

[tableOfContents]
    endLevel = 4
    startLevel = 2

[highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
