defaultFeaturedImage = "/img/straddie.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
#logo = "img/bear.jpg"
    

mainSections = ["posts"]

[header]
  layout = "fixed"

[article]
  showDate = false
  showDateOnlyInArticle = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showDraftLabel = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthorsBadges = true
  showWordCount = false
  showSummary = true

[list]
  showHero = true
  heroStyle = "background"
  cardView = true
  groupByYear = false
  cardViewScreenWidth = false
  showSummary = true

[homepage]
  layout = "background" # valid options: page, profile, custom
  homepageImage = "/img/beach.jpg"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = '/posts'
  cardView = false
  cardViewScreenWidth = true
  layoutBackgroundBlur = false

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true