name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: blog/public
        clean: true
        single-commit: true